title: basicblog
email: chompoo@gang500.ml
description: >-
  A basic blog with features as you might expect.
baseurl: "/basicblog"
url: "https://chompoo500ml.github.io"
github_username: chompoo500ml

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
